# 4.05 Para saber mais: bloco try/catch
Implementamos no código o que chamamos de **bloco try/catch** para “separar” os casos de sucesso das falhas no processamento das requisições.

O `try/catch` é uma estrutura usada justamente quando é necessário capturar e manejar erros de forma mais precisa, permitindo que os erros sejam “capturados e tratados” internamente pela função e evitando que a aplicação pare de funcionar ou que o cliente receba respostas inesperadas.

- No **bloco `try`** inserimos o código que é necessário “monitorar” para que potenciais erros sejam capturados, como operações em bases de dados ou APIs externas. Em caso de sucessos, apenas o código dentro do `try` é executado e seus resultados retornados para fora da função, conforme o caso.
- No **bloco `catch`** inserimos o código que vai ser executado em caso de erros ocorridos no código que está dentro do `try`. Qualquer erro que aconteça dentro do `try` é automaticamente lançado para dentro do `catch` e recebido através do parâmetro que normalmente chamamos de `(error)` ou `(e)`. Uma vez dentro do `catch` o erro pode ser tratado de acordo e debugado, e o lado cliente pode receber uma resposta que faça sentido.

O `try/catch` funciona também para captura e tratamento de possíveis erros em operações assíncronas, como as que envolvem justamente operações em bancos ou outras APIs.

Tratamento de erros é uma parte importante do desenvolvimento de uma API. Após finalizarmos nossa API, você vai ter a oportunidade de continuar praticando no [próximo curso da formação de Node.js com Express](https://cursos.alura.com.br/course/node-js-buscas-filtros-paginacao-erros-api).